# Generated by Django 4.2.7 on 2024-03-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='film',
            name='review',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
