# Generated by Django 4.2.7 on 2024-03-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_film_rating_film_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='category',
        ),
    ]
